/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sau.quiz;

import java.awt.Font;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ratip
 */
public class FrmSAUCoffeeshop extends javax.swing.JFrame {

    /**
     * Creates new form FrmSAUCoffeeshop
     */
    public FrmSAUCoffeeshop() {
        initComponents();
        
        setIconImage(
                Toolkit.getDefaultToolkit().getImage(
                        getClass().getResource("/sau/quiz/image/coffee.jpg")
                )
        );
        
        UIManager.put("OptionPane.messageFont", new Font("tahoma", Font.PLAIN, 12));
        setLocationRelativeTo(getRootPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cbVL1 = new javax.swing.JCheckBox();
        cbVL2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfVL1 = new javax.swing.JTextField();
        tfVL2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbSC2 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        tfSC2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfSC1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbSC1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfIL1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbIL1 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbIL2 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        tfIL2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfSL1 = new javax.swing.JTextField();
        tfSL2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cbSL1 = new javax.swing.JCheckBox();
        cbSL2 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cbM1 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfM1 = new javax.swing.JTextField();
        tfM2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cbM2 = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        tfUT2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cbUT2 = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cbUT1 = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        tfUT1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltSale = new javax.swing.JList<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCoffeeOrder = new javax.swing.JTextArea();
        lbTotalPrice = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btCal = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAU COFFEESHOP (Coffee Blend) Created by 6552410024");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/coffee.jpg"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SAU COFFEESHOP");
        jLabel2.setOpaque(true);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/a.jpg"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VANILLA LATTE");
        jLabel4.setOpaque(true);

        cbVL1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbVL1.setText("ร้อน");

        cbVL2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbVL2.setText("เย็น");
        cbVL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVL2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("จำนวน");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("จำนวน");

        tfVL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfVL1KeyTyped(evt);
            }
        });

        tfVL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfVL2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("แก้ว");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("แก้ว");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("ร้อน 40 บาท/แก้ว เย็น 60 บาท/แก้ว");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/b.jpg"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ร้อน 45 บาท/แก้ว เย็น 65 บาท/แก้ว");

        cbSC2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSC2.setText("เย็น");
        cbSC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSC2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("จำนวน");

        tfSC2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSC2KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("แก้ว");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("แก้ว");

        tfSC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSC1KeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("จำนวน");

        cbSC1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSC1.setText("ร้อน");

        jLabel16.setBackground(new java.awt.Color(255, 102, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SKINNY CAPPUCCINO");
        jLabel16.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("แก้ว");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("แก้ว");

        tfIL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIL1KeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("จำนวน");

        cbIL1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbIL1.setText("ร้อน");

        jLabel20.setBackground(new java.awt.Color(255, 102, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("IRISH LATTE");
        jLabel20.setOpaque(true);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/c.jpg"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("ร้อน 40 บาท/แก้ว เย็น 60 บาท/แก้ว");

        cbIL2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbIL2.setText("เย็น");
        cbIL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIL2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("จำนวน");

        tfIL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIL2KeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("จำนวน");

        tfSL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSL1KeyTyped(evt);
            }
        });

        tfSL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSL2KeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("แก้ว");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("แก้ว");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("ร้อน 50 บาท/แก้ว เย็น 70 บาท/แก้ว");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/d.jpg"))); // NOI18N

        jLabel29.setBackground(new java.awt.Color(255, 102, 0));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("SKINNY LATTE");
        jLabel29.setOpaque(true);

        cbSL1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSL1.setText("ร้อน");

        cbSL2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSL2.setText("เย็น");
        cbSL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSL2ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("จำนวน");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("จำนวน");

        cbM1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbM1.setText("ร้อน");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("แก้ว");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("ร้อน 40 บาท/แก้ว เย็น 60 บาท/แก้ว");

        tfM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfM1KeyTyped(evt);
            }
        });

        tfM2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfM2KeyTyped(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("จำนวน");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("แก้ว");

        jLabel36.setBackground(new java.awt.Color(255, 102, 0));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("MOCHA");
        jLabel36.setOpaque(true);

        cbM2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbM2.setText("เย็น");
        cbM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbM2ActionPerformed(evt);
            }
        });

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/e.jpg"))); // NOI18N

        tfUT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUT2KeyTyped(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("จำนวน");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("แก้ว");

        jLabel40.setBackground(new java.awt.Color(255, 102, 0));
        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("UNSWEETENED TASTE");
        jLabel40.setOpaque(true);

        cbUT2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbUT2.setText("เย็น");
        cbUT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUT2ActionPerformed(evt);
            }
        });

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/f.jpg"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("จำนวน");

        cbUT1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbUT1.setText("ร้อน");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("แก้ว");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setText("ร้อน 45 บาท/แก้ว เย็น 65 บาท/แก้ว");

        tfUT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUT1KeyTyped(evt);
            }
        });

        ltSale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ltSale.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "บุคคลทั่วไป ไม่มีส่วนลด", "นักศึกษา ม.เอเชีย ลด 10%", "นักศึกษา ม.เอเชีย (ต่างชาติ) ลด 7%", "บุคลากร ม.เอเชีย ลด 5%" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ltSale);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setText("ส่วนลด (กรณีมีส่วนลดให้แสดงบัตรฯ)");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setText("รายการกาแฟที่สั่ง");

        taCoffeeOrder.setColumns(20);
        taCoffeeOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taCoffeeOrder.setRows(5);
        jScrollPane2.setViewportView(taCoffeeOrder);

        lbTotalPrice.setBackground(new java.awt.Color(255, 204, 0));
        lbTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTotalPrice.setForeground(new java.awt.Color(255, 0, 0));
        lbTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalPrice.setText("0.00");
        lbTotalPrice.setOpaque(true);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setText("ค่ากาแฟรวมทั้งสิ้นเป็นเงิน (บาท)");

        btCal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sau/quiz/image/cal.png"))); // NOI18N
        btCal.setText("คำนวณ");
        btCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalActionPerformed(evt);
            }
        });

        btReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btReset.setText("รีเซ็ต");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSL2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSL1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel30)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfSL2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tfSL1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel25))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel26))))
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbM2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbM1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel31)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfM2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tfM1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel35))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel32))))
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbUT2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbUT1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel42)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfUT2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tfUT1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel39))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel43))))
                                    .addComponent(jLabel44)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbVL2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbVL1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfVL2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tfVL1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel8)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSC2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSC1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfSC2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tfSC1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel13))))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbIL2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbIL1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel19)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfIL2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tfIL1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel17))))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbVL1)
                            .addComponent(jLabel5)
                            .addComponent(tfVL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbVL2)
                            .addComponent(jLabel6)
                            .addComponent(tfVL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSC1)
                            .addComponent(jLabel15)
                            .addComponent(tfSC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSC2)
                            .addComponent(jLabel12)
                            .addComponent(tfSC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(jLabel21)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbIL1)
                            .addComponent(jLabel19)
                            .addComponent(tfIL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbIL2)
                            .addComponent(jLabel23)
                            .addComponent(tfIL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSL1)
                            .addComponent(jLabel30)
                            .addComponent(tfSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSL2)
                            .addComponent(jLabel24)
                            .addComponent(tfSL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addComponent(jLabel37)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbM1)
                            .addComponent(jLabel31)
                            .addComponent(tfM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbM2)
                            .addComponent(jLabel34)
                            .addComponent(tfM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33))
                    .addComponent(jLabel41)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbUT1)
                            .addComponent(jLabel42)
                            .addComponent(tfUT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbUT2)
                            .addComponent(jLabel38)
                            .addComponent(tfUT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(jLabel48))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVL2ActionPerformed

    private void cbSC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSC2ActionPerformed

    private void cbIL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIL2ActionPerformed

    private void cbSL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSL2ActionPerformed

    private void cbM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbM2ActionPerformed

    private void cbUT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUT2ActionPerformed

    private void btCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalActionPerformed
        // TODO add your handlingฟไำ code here:
        taCoffeeOrder.setText("");

        double priceVL1 = 0;
        if (cbVL1.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfVL1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน VANILLA LATTE แบบร้อน",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceVL1 = Double.parseDouble(tfVL1.getText().trim()) * 40;
                taCoffeeOrder.append("VANILLA LATTE ร้อน " + tfVL1.getText().trim() + " แก้ว\n");
            }
        }

        double priceVL2 = 0;
        if (cbVL2.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfVL2.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน VANILLA LATTE แบบเย็น",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceVL2 = Double.parseDouble(tfVL2.getText().trim()) * 60;
                taCoffeeOrder.append("VANILLA LATTE เย็น " + tfVL2.getText().trim() + " แก้ว\n");
            }
        }

        double priceSC1 = 0;
        if (cbSC1.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfSC1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน SKINNY CAPPUCCINO แบบร้อน",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceSC1 = Double.parseDouble(tfSC1.getText().trim()) * 45;
                taCoffeeOrder.append("SKINNY CAPPUCCINO ร้อน " + tfSC1.getText().trim() + " แก้ว\n");
            }
        }

        double priceSC2 = 0;
        if (cbSC2.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfSC2.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน SKINNY CAPPUCCINO แบบเย็น",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceSC2 = Double.parseDouble(tfSC2.getText().trim()) * 65;
                taCoffeeOrder.append("SKINNY CAPPUCCINO เย็น " + tfSC2.getText().trim() + " แก้ว\n");
            }
        }

        double priceIL1 = 0;
        if (cbIL1.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfIL1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวนกาแฟ IRISH LATTE แบบร้อน",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceIL1 = Double.parseDouble(tfIL1.getText().trim()) * 40;
                taCoffeeOrder.append("IRISH LATTE ร้อน " + tfIL1.getText().trim() + " แก้ว\n");
            }
        }

        double priceIL2 = 0;
        if (cbIL2.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfIL2.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวนกาแฟ IRISH LATTE แบบเย็น",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceIL2 = Double.parseDouble(tfIL2.getText().trim()) * 60;
                taCoffeeOrder.append("IRISH LATTE เย็น " + tfIL2.getText().trim() + " แก้ว\n");
            }
        }

        double priceSL1 = 0;
        if (cbSL1.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfSL1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน SKINNY LATTE แบบร้อน",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceSL1 = Double.parseDouble(tfSL1.getText().trim()) * 50;
                taCoffeeOrder.append("SKINNY LATTE ร้อน " + tfSL1.getText().trim() + " แก้ว\n");
            }
        }

        double priceSL2 = 0;
        if (cbSL2.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfSL2.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน SKINNY LATTE แบบเย็น",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceSL2 = Double.parseDouble(tfSL2.getText().trim()) * 70;
                taCoffeeOrder.append("SKINNY LATTE เย็น " + tfSL2.getText().trim() + " แก้ว\n");
            }
        }

        double priceM1 = 0;
        if (cbM1.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfM1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน MOCHA แบบร้อน",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceM1 = Double.parseDouble(tfM1.getText().trim()) * 40;
                taCoffeeOrder.append("MOCHA ร้อน " + tfM1.getText().trim() + " แก้ว\n");
            }
        }

        double priceM2 = 0;
        if (cbM2.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfM2.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวนแก้ว MOCHA แบบเย็น",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceM2 = Double.parseDouble(tfM2.getText().trim()) * 60;
                taCoffeeOrder.append("MOCHA เย็น " + tfM2.getText().trim() + " แก้ว\n");
            }
        }

        double priceUT1 = 0;
        if (cbUT1.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfUT1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน UNSWEETENED TASTE แบบร้อน",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceUT1 = Double.parseDouble(tfUT1.getText().trim()) * 45;
                taCoffeeOrder.append("UNSWEETENED TASTE ร้อน " + tfUT1.getText().trim() + " แก้ว\n");
            }
        }

        double priceUT2 = 0;
        if (cbUT2.isSelected() == true) { //ตรวจว่าเลือก checkbox นี้หรือยัง
            if (tfUT2.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "โปรดใส่จำนวน UNSWEETENED TASTE แบบเย็น",
                        "คำเตือน!!", JOptionPane.WARNING_MESSAGE);
            } else {
                priceUT2 = Double.parseDouble(tfUT2.getText().trim()) * 65;
                taCoffeeOrder.append("UNSWEETENED TASTE เย็น " + tfUT2.getText().trim() + " แก้ว\n");
            }
        }

        double prePrice = priceVL1 + priceVL2 + priceSC1 + priceSC2 + priceIL1 + priceIL2
                + priceSL1 + priceSL2 + priceM1 + priceM2 + priceUT1 + priceUT2;

        double posePrice = 0;
        if (ltSale.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "โปรดเลือกส่วนลดก่อน!!!",
                    "คำเตือน", JOptionPane.WARNING_MESSAGE);
        } else {
            if (ltSale.getSelectedIndex() == 0) {
                posePrice = prePrice;
            }

            if (ltSale.getSelectedIndex() == 1) {
                posePrice = prePrice - (prePrice * 10 / 100);
            }

            if (ltSale.getSelectedIndex() == 2) {
                posePrice = prePrice - (prePrice * 7 / 100);
            }

            if (ltSale.getSelectedIndex() == 3) {
                posePrice = prePrice - (prePrice * 5 / 100);
            }
        }

        lbTotalPrice.setText(new DecimalFormat("0.00").format(posePrice));
    }//GEN-LAST:event_btCalActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        cbVL1.setSelected(false);
        cbVL2.setSelected(false);
        cbSC1.setSelected(false);
        cbSC2.setSelected(false);
        cbIL1.setSelected(false);
        cbIL2.setSelected(false);
        cbSL1.setSelected(false);
        cbSL2.setSelected(false);
        cbM1.setSelected(false);
        cbM2.setSelected(false);
        cbUT1.setSelected(false);
        cbUT2.setSelected(false);
        
        tfVL1.setText("");
        tfVL2.setText("");
        tfSC1.setText("");
        tfSC2.setText("");
        tfIL1.setText("");
        tfIL2.setText("");
        tfSL1.setText("");
        tfSL2.setText("");
        tfM1.setText("");
        tfM2.setText("");
        tfUT1.setText("");
        tfUT2.setText("");
        
        ltSale.setSelectedIndex(0);
        taCoffeeOrder.setText("");
        lbTotalPrice.setText("0.00");
    }//GEN-LAST:event_btResetActionPerformed

    private void tfVL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVL1KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfVL1KeyTyped

    private void tfVL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVL2KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfVL2KeyTyped

    private void tfSC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSC1KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSC1KeyTyped

    private void tfSC2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSC2KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSC2KeyTyped

    private void tfIL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIL1KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfIL1KeyTyped

    private void tfIL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIL2KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfIL2KeyTyped

    private void tfSL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSL1KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSL1KeyTyped

    private void tfSL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSL2KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSL2KeyTyped

    private void tfM1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfM1KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfM1KeyTyped

    private void tfM2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfM2KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfM2KeyTyped

    private void tfUT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUT1KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfUT1KeyTyped

    private void tfUT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUT2KeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfUT2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSAUCoffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSAUCoffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSAUCoffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSAUCoffeeshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSAUCoffeeshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCal;
    private javax.swing.JButton btReset;
    private javax.swing.JCheckBox cbIL1;
    private javax.swing.JCheckBox cbIL2;
    private javax.swing.JCheckBox cbM1;
    private javax.swing.JCheckBox cbM2;
    private javax.swing.JCheckBox cbSC1;
    private javax.swing.JCheckBox cbSC2;
    private javax.swing.JCheckBox cbSL1;
    private javax.swing.JCheckBox cbSL2;
    private javax.swing.JCheckBox cbUT1;
    private javax.swing.JCheckBox cbUT2;
    private javax.swing.JCheckBox cbVL1;
    private javax.swing.JCheckBox cbVL2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTotalPrice;
    private javax.swing.JList<String> ltSale;
    private javax.swing.JTextArea taCoffeeOrder;
    private javax.swing.JTextField tfIL1;
    private javax.swing.JTextField tfIL2;
    private javax.swing.JTextField tfM1;
    private javax.swing.JTextField tfM2;
    private javax.swing.JTextField tfSC1;
    private javax.swing.JTextField tfSC2;
    private javax.swing.JTextField tfSL1;
    private javax.swing.JTextField tfSL2;
    private javax.swing.JTextField tfUT1;
    private javax.swing.JTextField tfUT2;
    private javax.swing.JTextField tfVL1;
    private javax.swing.JTextField tfVL2;
    // End of variables declaration//GEN-END:variables
}
